classDiagram
    direction LR
    class QuestStatus {
        <<enum>>
        active
        inactive
        completed
    }

    class QuestObjective {
        progress: Float
        target: Float
        description: String
        isCompleted: Bool
        init()
        setProgress(Float)
    }
    
    class QuestCriteria {
        eventType: EventType
        requiredData: [EventDataType: any Hashable]
        progressCalculator: ProgressCalculator
    }

    class Reward

    class RewardType {
        <<enum>>
        xp
        currency
        item
    }
    
    class SpecificReward {
        <<interface>>
        +RewardType type
    }

    class QuestComponent {
        progress: Float
        isCompleted: Bool
        init()
    }

    class Quest {
        init()
    }

    class QuestSystem {
        init()
        getCurrentQuest() QuestComponent
        getAllQuests() [QuestComponent]
        addQuest(QuestComponent)
        updateCurrenctQuestProgress(QuestObjective)
        moveToNextQuest()
    }
    
    QuestCriteria "1" -- "1" QuestObjective: criteria
    QuestObjective "*" -- "1" QuestComponent: objectives
    QuestStatus "1" -- "1" QuestComponent: status
    Reward "*" -- "1" QuestComponent: completionReward
    QuestComponent "1" <-- "1" Quest : component
    QuestComponent -- QuestSystem : components
    SpecificRewards "*" -- "1" Reward : rewards
